---
kind: pipeline
name: upload-release

platform:
  os: linux
  arch: amd64

# Build and upload release when repository is tagged with a v1.* tag
trigger:
  ref:
  - "refs/tags/v1.*"
  event:
  - tag

steps:
- name: build
  pull: default
  image: node:14
  environment:
    VERSION: ${DRONE_TAG##v}
  commands:
  - ./scripts/build

- name: upload
  pull: default
  image: plugins/gcs
  settings:
  when:
    instance:
      - drone-publish.rancher.io  
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_TAG##v}.tar.gz
    target: releases.rancher.com/api-ui/${DRONE_TAG##v}.tar.gz
    token:
      from_secret: google_auth_key
