#!/usr/bin/env node

var assets = require('gd-assets');

var groups    = assets.groups.load(__dirname+'/assets.json');
var pkg       = require('./package.json');
var outputDir = __dirname+'/compiled';

assets.compile(groups, pkg, outputDir);
