name: check-build
on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: Setup Node.js
      uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
      with:
        node-version: '24.x'
    - name: Validate build
      run: |
        yarn install --frozen-lockfile
        yarn run build
